application: cyphme
version: master
runtime: go
api_version: go1

handlers:
- url: /anal/.*
  static_files: anal.html
  upload: anal.html
  # default_headers Content-Security-Policy X-Frame-Options

- url: .*
  script: _go_app
  secure: always
