application: cyphme
version: master
runtime: go
api_version: go1

handlers:
- url: /anal/.*
  static_files: anal.html
  upload: anal.html
  http_headers:
    Cache-Control: public, max-age=0
    Public-Key-Pins: max-age=31536000; includeSubdomains; pin-sha256="8jdS3zcG5kUApHWDrLH5Q8wEygqGbGEhYApjSDtufBU="; pin-sha256="AMRT67hN1KPI+u7Aw9JpZlzyRaKeO+6u2H+jtOmWVy8="
    Strict-Transport-Security: max-age=31536000; includeSubdomains

- url: .*
  script: _go_app
  secure: always
